name: LitElement
description: A simple base class for creating fast, lightweight web components
exclude: [package.json, polymer.json, src, node_modules, package-lock.json]
markdown: kramdown
kramdown:
  parse_block_html: true
google_analytics: UA-39334307-23
projects: includes/projects
collections:
  includes:
    output: true
  guide:
    output: true
    permalink: /:collection/:title
  try: 
    output: true
    permalink: /:collection/:title
include:
  - "_*_.html"
  - "_*_.*.html"
